baseURL = "https://blog.luisrego.com/"
title = "Luís Sousa Rêgo"
languageCode = 'en-us'
theme = "Ardeidae"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[params]
github = "https://github.com/LuisSousaRego"
dateform = "2006-01-02"
email = "luis.sousa.rego@gmail.com"
