baseURL = "https://overcomingpoorprogramming.com/"
title = "Overcoming poor programming"
paginate = 10
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "G-M8TQYW9J99"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Overcoming poor programming"
description = """
My name is Luís and I am a software developer. 
Here I write about my projects and experiences, mostly related to programming.
"""
keywords = ["Blog", "Software Development", "Programming"]
author = "Luís Sousa Rêgo"
images = ["<link or path of image for opengraph, twitter-cards>"]
DateFormat = "2006-01-02"
defaultTheme = "light"
disableThemeToggle = true
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = true
showtoc = false
tocopen = false

[params.assets]
favicon = "favicon.ico"
favicon16x16 = "favicon.ico"
favicon32x32 = "favicon.ico"
apple_touch_icon = "favicon.ico"
safari_pinned_tab = "favicon.ico"

[params.profileMode]
enabled = false

[params.homeInfoParams]
Title = "Hey there!"
Content = """
My name is Luís and I am a software developer.
- Here I write about my projects and experiences, mostly related to programming. 
- You can also find me on the following:
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/LuisSousaRego"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/luissousarego/"

[[params.socialIcons]]
name = "rss"
url = "https://overcomingpoorprogramming.blog/index.xml"

[params.analytics.google]
SiteVerificationTag = "G-M8TQYW9J99"

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true
